spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: https://www.qq.com
        predicates:
        - Query=green
      - id: admin_route
        uri: lb://renren-fast
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
## 前端项目， /api